### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by sull** [phediverse/mastodon-rest#5]
I get a 401 Unauthorized response: `{"error":"The access token is invalid"}` after reloading page (the initial API request using token works).

**Comment by iansltx** [comment]
Please provide more information about your issue, including the calls you're making to the library to get where you're seeing this error.

**Comment by sull** [comment]
Sorry, disregard. I was not saving the access token properly and was injecting the code from url param on subsequent requests.
